### ISSUE TITLE
Translucent material (leaf texture)

### ISSUE THREAD

**Issue by whaciathy** [DaveFace/UnrealRetroShaders#4]
Transluced materials I created a leaf texture material I used the Transluced option and when I enter the game the fog makes the texture not display properly

(if you don't understand something I'm sorry but my English is not the best and I use a translator so I apologize)

Screen from game:
![image](https://user-images.githubusercontent.com/113856481/190923775-d7493cbb-139b-47e6-9924-46136a9d3368.png)

Material Bp:
![image](https://user-images.githubusercontent.com/113856481/190923811-624743d3-2ca6-490f-bfa0-28dea5ef45b1.png)

**Comment by DaveFace** [comment]
Sorry, only just saw this. If you're still having the problem, it's because of where the fog is being applied in the render pipe - open the fog post process material and change the blendable location. Before translucency should probably work, if it isn't already set to that. Or you could try a masked alpha for the leaves instead.
